services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jbcast_web
    command: gunicorn jbcast_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jbcast_celery
    command: celery -A jbcast_backend worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web

  redis:
    image: redis:7
    container_name: jbcast_redis
    ports:
      - "6379:6379"
